### ISSUE TITLE
DnD to DeskNotes changes the target's color

### ISSUE THREAD

**Issue by sfanxiang** [HaikuArchives/DeskNotes#15]
![img_20180112_083741](https://user-images.githubusercontent.com/5893440/34854420-927f5610-f774-11e7-96a8-a35fc7bd6d0c.jpg)
Notice the color of "Copyright 2000" is different because it's dragged from another note.

**Comment by humdingerb** [comment]
Can't reproduce. Can you give a step-by-step how exactly you d'n'd from where to where, into replicant or DeskNotes app etc.?

**Comment by sfanxiang** [comment]
It actually requires restarting the app. I didn't notice this.

To reproduce:
1. Change the text color in the app.
2. Create a replicant.
3. Restart the app. The text is in the changed color.
4. Drag some text from the replicant to the app. The text color is wrong.

**Comment by humdingerb** [comment]
Now I see it, thanks. So probably the dropped text always gets the default black, instead of respecting the currently set colour.

**Comment by humdingerb** [comment]
Doesn't apply since version 1.2 anymore. Text colour isn't set anymore, but computed with the background colour.
