### ISSUE TITLE
Add a tool to highlight selected text

### ISSUE THREAD

**Issue by sfanxiang** [HaikuArchives/DeskNotes#16]
Highlighting is quite often found in note apps. It would be convenient to have this feature.

**Comment by humdingerb** [comment]
It does highlight here... Can you elaborate?

**Comment by sfanxiang** [comment]
Updated to clarify a bit.

**Comment by humdingerb** [comment]
Oh, I see. Then it's quite similar to #17 .
For that one, too, I can imagine we'll have to wait for an extended styled BTextView. That will kill all those birds with one rather large stone.
