### ISSUE TITLE
Missing `findpaths` command on Debian (my mistke)

### ISSUE THREAD

**Issue by rysson** [HaikuArchives/DeskNotes#28]
I can not build your project.
What should the `findpaths` command do? And how I could replace it?

```bash
$ make
/bin/sh: 1: findpaths: not found
Makefile:132: /etc/makefile-engine: No such file or directory
make: *** No rule to make target '/etc/makefile-engine'.  Stop.
```

**Comment by humdingerb** [comment]
The app only builds and runs under [Haiku](https://www.haiku-os.org/). I guess you're running another OS?

**Comment by rysson** [comment]
Oh, I missed it. Sure, I'm on Debian.
Sorry for a confusion.

**Comment by humdingerb** [comment]
No problem, you can give it a try with Haiku in a VM. :)
