### ISSUE TITLE
Pin note

### ISSUE THREAD

**Issue by vanishakesswani** [HaikuArchives/DeskNotes#7]
I want to pin my note so that it's always on top of the windows/other notes but there is no option to pin notes .

**Comment by humdingerb** [comment]
That's not possible with replicants. They don't overlap reliably. If a replicant handle is on top of another replicant, you may not even be able to grab the handle anymore. Avoid.
Since the replicants are the basis for DeskNotes, this only something that could be enhanced at Haiku itself.
